
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
recorder: !include recorder.yaml
scene: !include scenes.yaml

google:
  client_id: !secret GOOGLE_CLIENT_ID
  client_secret: !secret GOOGLE_CLIENT_SECRET
  track_new_calendar: false
